export const Posts = [
    {
        id: 1,
        img: "./assets/posts/overlay/yt.webp",
        video: "./assets/posts/yt.webp",
        profileImg: "./assets/img/marina.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "linguamarina",
        views: "2.1M",
        time: "2 months",
        length: "14:25",
        checked: true,
    },
    {
        id: 2,
        img: "./assets/posts/overlay/yt2.webp",
        video: "./assets/posts/yt2.webp",
        profileImg: "./assets/img/ted.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "TEDx Talks",
        views: "32M",
        time: "5 years",
        length: "17:19",
        checked: true,
    },
    {
        id: 3,
        img: "./assets/posts/overlay/yt3.webp",
        video: "./assets/posts/yt3.webp",
        profileImg: "./assets/img/jadi.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "Jadi Mirmirani",
        views: "256K",
        time: "2 weeks",
        length: "1:48:51",
    },
    {
        id: 4,
        img: "./assets/posts/overlay/yt2.webp",
        video: "./assets/posts/yt5.webp",
        profileImg: "./assets/img/ted.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "TEDx Talks",
        views: "32M",
        time: "5 years",
        length: "24:35",
        checked: true,
    },
    {
        id: 5,
        img: "./assets/posts/overlay/yt4.webp",
        video: "./assets/posts/yt4.webp",
        profileImg: "./assets/img/alaei.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "Ali Alaei",
        views: "3.2K",
        time: "4 days",
        length: "5:58",
    },
    {
        id: 6,
        img: "./assets/posts/overlay/yt5.webp",
        video: "./assets/posts/yt6.webp",
        profileImg: "./assets/img/bbc.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "BBC News",
        views: "12.6M",
        time: "1 month",
        length: "48:51",
        checked: true,
    },
    {
        id: 7,
        img: "./assets/posts/overlay/yt6.webp",
        video: "./assets/posts/yt7.webp",
        profileImg: "./assets/img/marina.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "linguamarina",
        views: "45.3K",
        time: "2 weeks",
        length: "2:12:01",
        checked: true,
    },
    {
        id: 8,
        img: "./assets/posts/overlay/yt7.webp",
        video: "./assets/posts/yt8.webp",
        profileImg: "./assets/img/freeCode.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "freeCodeCamp.org",
        views: "188K",
        time: "6 months",
        length: "44:52",
    },
    {
        id: 9,
        img: "./assets/posts/overlay/yt8.webp",
        video: "./assets/posts/yt1.webp",
        profileImg: "./assets/img/arian.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "Arian Abrouni",
        views: "1.1K",
        time: "7 hours",
        length: "1:48:51",
    },
    {
        id: 10,
        img: "./assets/posts/overlay/yt.webp",
        video: "./assets/posts/yt.webp",
        profileImg: "./assets/img/marina.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "linguamarina",
        views: "2.1M",
        time: "2 months",
        length: "1:48:51",
        checked: true,
    },
    {
        id: 11,
        img: "./assets/posts/overlay/yt3.webp",
        video: "./assets/posts/yt3.webp",
        profileImg: "./assets/img/jadi.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "Jadi Mirmirani",
        views: "256K",
        time: "2 weeks",
        length: "1:48:51",
    },
    {
        id: 12,
        img: "./assets/posts/overlay/yt4.webp",
        video: "./assets/posts/yt4.webp",
        profileImg: "./assets/img/alaei.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "Ali Alaei",
        views: "3.2K",
        time: "4 days",
        length: "1:48:51",
    },
    {
        id: 13,
        img: "./assets/posts/overlay/yt5.webp",
        video: "./assets/posts/yt5.webp",
        profileImg: "./assets/img/bbc.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "BBC News",
        views: "12.6M",
        time: "1 month",
        length: "1:48:51",
        checked: true,
    },
    {
        id: 14,
        img: "./assets/posts/overlay/yt6.webp",
        video: "./assets/posts/yt6.webp",
        profileImg: "./assets/img/marina.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "linguamarina",
        views: "45.3K",
        time: "2 weeks",
        length: "1:48:51",
        checked: true,
    },
    {
        id: 15,
        img: "./assets/posts/overlay/yt7.webp",
        video: "./assets/posts/yt7.webp",
        profileImg: "./assets/img/freeCode.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "freeCodeCamp.org",
        views: "188K",
        time: "6 months",
        length: "1:48:51",
    },
    {
        id: 16,
        img: "./assets/posts/overlay/yt8.webp",
        video: "./assets/posts/yt8.webp",
        profileImg: "./assets/img/arian.jpg",
        desc: "After watching this, your brain will not be the same",
        profile: "Arian Abrouni",
        views: "1.1K",
        time: "7 hours",
        length: "1:48:51",
    },
];

export const HeaderItem = [
    {
        id: 1,
        desc: "All",
        active: true,
    },
    {
        id: 2,
        desc: "Conversation",
    },
    {
        id: 3,
        desc: "JavaScript",
    },
    {
        id: 4,
        desc: "Python",
    },
    {
        id: 5,
        desc: "Eating",
    },
    {
        id: 6,
        desc: "Stocks",
    },
    {
        id: 7,
        desc: "Elon Musk",
    },
    {
        id: 8,
        desc: "Web Development",
    },
    {
        id: 9,
        desc: "TED",
    },
    {
        id: 10,
        desc: "Laptops",
    },
    {
        id: 11,
        desc: "Elon Musk",
    },
];
